language: python
python:
  - 2.6
  - 2.7
  - 3.2
install:
  - pip install nose
  - pip install webob
  - pip install webtest
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install beautifulsoup; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install beautifulsoup; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install beautifulsoup; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install restkit; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install restkit; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install restkit; fi"
  - python setup.py develop
script:
  - nosetests -s -v
