---

name: tox

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      MOZ_HEADLESS: "1"
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10", 3.11, 3.12]

    steps:
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install geckodriver
        run: tests/geckodriver.sh
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: |
          export PATH=$PATH:$PWD
          tox -e py
      - name: Run lint / docs
        run: tox -e lint,docs
        if: matrix.python == 3.11

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10", 3.11, 3.12]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10", 3.11, 3.12]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py
